# http://www.appveyor.com/docs/appveyor-yml

# init:
#   - git config --global core.autocrlf true

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  - md C:\nc
  - npm config set cache C:\nc
  - npm version
  - npm install --no-optional

cache:
  - '%APPDATA%\npm-cache'
  - '%APPDATA%\Roaming\bower'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - cmd: npm run test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
